remote_theme: chrisrhymes/bulma-clean-theme
include:
  - "_*_.md"
  - "_*_.*.md"
  - "_*_.html"
  - "_*_.*.html"
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      author: "Nicolas Boyer"
      layout: page
      show_sidebar: false

theme: jekyll-theme-leap-day