(function(){
    'use strict';var h=new function(){};var aa=new Set("annotation-xml color-profile font-face font-face-src font-face-uri font-face-format font-face-name missing-glyph".split(" "));function m(b){var a=aa.has(b);b=/^[a-z][.0-9_a-z]*-[\-.0-9_a-z]*$/.test(b);return!a&&b}function n(b){var a=b.isConnected;if(void 0!==a)return a;for(;b&&!(b.__CE_isImportDocument||b instanceof Document);)b=b.parentNode||(window.ShadowRoot&&b instanceof ShadowRoot?b.host:void 0);return!(!b||!(b.__CE_isImportDocument||b instanceof Document))}
    function p(b,a){for(;a&&a!==b&&!a.nextSibling;)a=a.parentNode;return a&&a!==b?a.nextSibling:null}
    function t(b,a,c){c=c?c:new Set;for(var d=b;d;){if(d.nodeType===Node.ELEMENT_NODE){var e=d;a(e);var f=e.localName;if("link"===f&&"import"===e.getAttribute("rel")){d=e.import;if(d instanceof Node&&!c.has(d))for(c.add(d),d=d.firstChild;d;d=d.nextSibling)t(d,a,c);d=p(b,e);continue}else if("template"===f){d=p(b,e);continue}if(e=e.__CE_shadowRoot)for(e=e.firstChild;e;e=e.nextSibling)t(e,a,c)}d=d.firstChild?d.firstChild:p(b,d)}}function u(b,a,c){b[a]=c};function v(){this.a=new Map;this.s=new Map;this.f=[];this.b=!1}function ba(b,a,c){b.a.set(a,c);b.s.set(c.constructor,c)}function w(b,a){b.b=!0;b.f.push(a)}function x(b,a){b.b&&t(a,function(a){return y(b,a)})}function y(b,a){if(b.b&&!a.__CE_patched){a.__CE_patched=!0;for(var c=0;c<b.f.length;c++)b.f[c](a)}}function z(b,a){var c=[];t(a,function(b){return c.push(b)});for(a=0;a<c.length;a++){var d=c[a];1===d.__CE_state?b.connectedCallback(d):A(b,d)}}
    function B(b,a){var c=[];t(a,function(b){return c.push(b)});for(a=0;a<c.length;a++){var d=c[a];1===d.__CE_state&&b.disconnectedCallback(d)}}
    function C(b,a,c){c=c?c:{};var d=c.w||new Set,e=c.i||function(a){return A(b,a)},f=[];t(a,function(a){if("link"===a.localName&&"import"===a.getAttribute("rel")){var c=a.import;c instanceof Node&&(c.__CE_isImportDocument=!0,c.__CE_hasRegistry=!0);c&&"complete"===c.readyState?c.__CE_documentLoadHandled=!0:a.addEventListener("load",function(){var c=a.import;if(!c.__CE_documentLoadHandled){c.__CE_documentLoadHandled=!0;var f=new Set(d);f.delete(c);C(b,c,{w:f,i:e})}})}else f.push(a)},d);if(b.b)for(a=0;a<
    f.length;a++)y(b,f[a]);for(a=0;a<f.length;a++)e(f[a])}
    function A(b,a){if(void 0===a.__CE_state){var c=a.ownerDocument;if(c.defaultView||c.__CE_isImportDocument&&c.__CE_hasRegistry)if(c=b.a.get(a.localName)){c.constructionStack.push(a);var d=c.constructor;try{try{if(new d!==a)throw Error("The custom element constructor did not produce the element being upgraded.");}finally{c.constructionStack.pop()}}catch(r){throw a.__CE_state=2,r;}a.__CE_state=1;a.__CE_definition=c;if(c.attributeChangedCallback)for(c=c.observedAttributes,d=0;d<c.length;d++){var e=c[d],
    f=a.getAttribute(e);null!==f&&b.attributeChangedCallback(a,e,null,f,null)}n(a)&&b.connectedCallback(a)}}}v.prototype.connectedCallback=function(b){var a=b.__CE_definition;a.connectedCallback&&a.connectedCallback.call(b)};v.prototype.disconnectedCallback=function(b){var a=b.__CE_definition;a.disconnectedCallback&&a.disconnectedCallback.call(b)};
    v.prototype.attributeChangedCallback=function(b,a,c,d,e){var f=b.__CE_definition;f.attributeChangedCallback&&-1<f.observedAttributes.indexOf(a)&&f.attributeChangedCallback.call(b,a,c,d,e)};function D(b,a){this.c=b;this.a=a;this.b=void 0;C(this.c,this.a);"loading"===this.a.readyState&&(this.b=new MutationObserver(this.f.bind(this)),this.b.observe(this.a,{childList:!0,subtree:!0}))}function E(b){b.b&&b.b.disconnect()}D.prototype.f=function(b){var a=this.a.readyState;"interactive"!==a&&"complete"!==a||E(this);for(a=0;a<b.length;a++)for(var c=b[a].addedNodes,d=0;d<c.length;d++)C(this.c,c[d])};function ca(){var b=this;this.b=this.a=void 0;this.f=new Promise(function(a){b.b=a;b.a&&a(b.a)})}function F(b){if(b.a)throw Error("Already resolved.");b.a=void 0;b.b&&b.b(void 0)};function G(b){this.j=!1;this.c=b;this.o=new Map;this.l=function(b){return b()};this.g=!1;this.m=[];this.u=new D(b,document)}
    G.prototype.define=function(b,a){var c=this;if(!(a instanceof Function))throw new TypeError("Custom element constructors must be functions.");if(!m(b))throw new SyntaxError("The element name '"+b+"' is not valid.");if(this.c.a.get(b))throw Error("A custom element with name '"+b+"' has already been defined.");if(this.j)throw Error("A custom element is already being defined.");this.j=!0;var d,e,f,r,k;try{var g=function(b){var a=l[b];if(void 0!==a&&!(a instanceof Function))throw Error("The '"+b+"' callback must be a function.");
    return a},l=a.prototype;if(!(l instanceof Object))throw new TypeError("The custom element constructor's prototype is not an object.");d=g("connectedCallback");e=g("disconnectedCallback");f=g("adoptedCallback");r=g("attributeChangedCallback");k=a.observedAttributes||[]}catch(q){return}finally{this.j=!1}a={localName:b,constructor:a,connectedCallback:d,disconnectedCallback:e,adoptedCallback:f,attributeChangedCallback:r,observedAttributes:k,constructionStack:[]};ba(this.c,b,a);this.m.push(a);this.g||
    (this.g=!0,this.l(function(){return da(c)}))};G.prototype.i=function(b){C(this.c,b)};function da(b){if(!1!==b.g){b.g=!1;for(var a=b.m,c=[],d=new Map,e=0;e<a.length;e++)d.set(a[e].localName,[]);C(b.c,document,{i:function(a){if(void 0===a.__CE_state){var e=a.localName,f=d.get(e);f?f.push(a):b.c.a.get(e)&&c.push(a)}}});for(e=0;e<c.length;e++)A(b.c,c[e]);for(;0<a.length;){for(var f=a.shift(),e=f.localName,f=d.get(f.localName),r=0;r<f.length;r++)A(b.c,f[r]);(e=b.o.get(e))&&F(e)}}}
    G.prototype.get=function(b){if(b=this.c.a.get(b))return b.constructor};G.prototype.whenDefined=function(b){if(!m(b))return Promise.reject(new SyntaxError("'"+b+"' is not a valid custom element name."));var a=this.o.get(b);if(a)return a.f;a=new ca;this.o.set(b,a);this.c.a.get(b)&&!this.m.some(function(a){return a.localName===b})&&F(a);return a.f};G.prototype.v=function(b){E(this.u);var a=this.l;this.l=function(c){return b(function(){return a(c)})}};window.CustomElementRegistry=G;
    G.prototype.define=G.prototype.define;G.prototype.upgrade=G.prototype.i;G.prototype.get=G.prototype.get;G.prototype.whenDefined=G.prototype.whenDefined;G.prototype.polyfillWrapFlushCallback=G.prototype.v;var H=window.Document.prototype.createElement,I=window.Document.prototype.createElementNS,ea=window.Document.prototype.importNode,fa=window.Document.prototype.prepend,ga=window.Document.prototype.append,ha=window.DocumentFragment.prototype.prepend,ia=window.DocumentFragment.prototype.append,J=window.Node.prototype.cloneNode,K=window.Node.prototype.appendChild,L=window.Node.prototype.insertBefore,M=window.Node.prototype.removeChild,N=window.Node.prototype.replaceChild,O=Object.getOwnPropertyDescriptor(window.Node.prototype,
    "textContent"),P=window.Element.prototype.attachShadow,Q=Object.getOwnPropertyDescriptor(window.Element.prototype,"innerHTML"),R=window.Element.prototype.getAttribute,S=window.Element.prototype.setAttribute,T=window.Element.prototype.removeAttribute,U=window.Element.prototype.getAttributeNS,ja=window.Element.prototype.setAttributeNS,ka=window.Element.prototype.removeAttributeNS,la=window.Element.prototype.insertAdjacentElement,ma=window.Element.prototype.insertAdjacentHTML,na=window.Element.prototype.prepend,
    oa=window.Element.prototype.append,V=window.Element.prototype.before,pa=window.Element.prototype.after,qa=window.Element.prototype.replaceWith,ra=window.Element.prototype.remove,sa=window.HTMLElement,W=Object.getOwnPropertyDescriptor(window.HTMLElement.prototype,"innerHTML"),ta=window.HTMLElement.prototype.insertAdjacentElement,ua=window.HTMLElement.prototype.insertAdjacentHTML;function va(){var b=X;window.HTMLElement=function(){function a(){var a=this.constructor,d=b.s.get(a);if(!d)throw Error("The custom element being constructed was not registered with `customElements`.");var e=d.constructionStack;if(!e.length)return e=H.call(document,d.localName),Object.setPrototypeOf(e,a.prototype),e.__CE_state=1,e.__CE_definition=d,y(b,e),e;var d=e.length-1,f=e[d];if(f===h)throw Error("The HTMLElement constructor was either called reentrantly for this constructor or called multiple times.");
    e[d]=h;Object.setPrototypeOf(f,a.prototype);y(b,f);return f}a.prototype=sa.prototype;Object.defineProperty(a.prototype,"constructor",{writable:!0,configurable:!0,enumerable:!1,value:a});return a}()};function Y(b,a,c){function d(a){return function(c){for(var e=[],d=0;d<arguments.length;++d)e[d-0]=arguments[d];for(var d=[],f=[],l=0;l<e.length;l++){var q=e[l];q instanceof Element&&n(q)&&f.push(q);if(q instanceof DocumentFragment)for(q=q.firstChild;q;q=q.nextSibling)d.push(q);else d.push(q)}a.apply(this,e);for(e=0;e<f.length;e++)B(b,f[e]);if(n(this))for(e=0;e<d.length;e++)f=d[e],f instanceof Element&&z(b,f)}}c.h&&(a.prepend=d(c.h));c.append&&(a.append=d(c.append))};function wa(){var b=X;u(Document.prototype,"createElement",function(a){if(this.__CE_hasRegistry){var c=b.a.get(a);if(c)return new c.constructor}a=H.call(this,a);y(b,a);return a});u(Document.prototype,"importNode",function(a,c){a=ea.call(this,a,c);this.__CE_hasRegistry?C(b,a):x(b,a);return a});u(Document.prototype,"createElementNS",function(a,c){if(this.__CE_hasRegistry&&(null===a||"http://www.w3.org/1999/xhtml"===a)){var d=b.a.get(c);if(d)return new d.constructor}a=I.call(this,a,c);y(b,a);return a});
    Y(b,Document.prototype,{h:fa,append:ga})};function xa(){var b=X;function a(a,d){Object.defineProperty(a,"textContent",{enumerable:d.enumerable,configurable:!0,get:d.get,set:function(a){if(this.nodeType===Node.TEXT_NODE)d.set.call(this,a);else{var e=void 0;if(this.firstChild){var c=this.childNodes,k=c.length;if(0<k&&n(this))for(var e=Array(k),g=0;g<k;g++)e[g]=c[g]}d.set.call(this,a);if(e)for(a=0;a<e.length;a++)B(b,e[a])}}})}u(Node.prototype,"insertBefore",function(a,d){if(a instanceof DocumentFragment){var e=Array.prototype.slice.apply(a.childNodes);
    a=L.call(this,a,d);if(n(this))for(d=0;d<e.length;d++)z(b,e[d]);return a}e=n(a);d=L.call(this,a,d);e&&B(b,a);n(this)&&z(b,a);return d});u(Node.prototype,"appendChild",function(a){if(a instanceof DocumentFragment){var c=Array.prototype.slice.apply(a.childNodes);a=K.call(this,a);if(n(this))for(var e=0;e<c.length;e++)z(b,c[e]);return a}c=n(a);e=K.call(this,a);c&&B(b,a);n(this)&&z(b,a);return e});u(Node.prototype,"cloneNode",function(a){a=J.call(this,a);this.ownerDocument.__CE_hasRegistry?C(b,a):x(b,a);
    return a});u(Node.prototype,"removeChild",function(a){var c=n(a),e=M.call(this,a);c&&B(b,a);return e});u(Node.prototype,"replaceChild",function(a,d){if(a instanceof DocumentFragment){var e=Array.prototype.slice.apply(a.childNodes);a=N.call(this,a,d);if(n(this))for(B(b,d),d=0;d<e.length;d++)z(b,e[d]);return a}var e=n(a),f=N.call(this,a,d),c=n(this);c&&B(b,d);e&&B(b,a);c&&z(b,a);return f});O&&O.get?a(Node.prototype,O):w(b,function(b){a(b,{enumerable:!0,configurable:!0,get:function(){for(var a=[],b=
    0;b<this.childNodes.length;b++)a.push(this.childNodes[b].textContent);return a.join("")},set:function(a){for(;this.firstChild;)M.call(this,this.firstChild);K.call(this,document.createTextNode(a))}})})};function ya(b){var a=Element.prototype;function c(a){return function(e){for(var c=[],d=0;d<arguments.length;++d)c[d-0]=arguments[d];for(var d=[],k=[],g=0;g<c.length;g++){var l=c[g];l instanceof Element&&n(l)&&k.push(l);if(l instanceof DocumentFragment)for(l=l.firstChild;l;l=l.nextSibling)d.push(l);else d.push(l)}a.apply(this,c);for(c=0;c<k.length;c++)B(b,k[c]);if(n(this))for(c=0;c<d.length;c++)k=d[c],k instanceof Element&&z(b,k)}}V&&(a.before=c(V));V&&(a.after=c(pa));qa&&u(a,"replaceWith",function(a){for(var e=
    [],c=0;c<arguments.length;++c)e[c-0]=arguments[c];for(var c=[],d=[],k=0;k<e.length;k++){var g=e[k];g instanceof Element&&n(g)&&d.push(g);if(g instanceof DocumentFragment)for(g=g.firstChild;g;g=g.nextSibling)c.push(g);else c.push(g)}k=n(this);qa.apply(this,e);for(e=0;e<d.length;e++)B(b,d[e]);if(k)for(B(b,this),e=0;e<c.length;e++)d=c[e],d instanceof Element&&z(b,d)});ra&&u(a,"remove",function(){var a=n(this);ra.call(this);a&&B(b,this)})};function za(){var b=X;function a(a,c){Object.defineProperty(a,"innerHTML",{enumerable:c.enumerable,configurable:!0,get:c.get,set:function(a){var e=this,d=void 0;n(this)&&(d=[],t(this,function(a){a!==e&&d.push(a)}));c.set.call(this,a);if(d)for(var f=0;f<d.length;f++){var r=d[f];1===r.__CE_state&&b.disconnectedCallback(r)}this.ownerDocument.__CE_hasRegistry?C(b,this):x(b,this);return a}})}function c(a,c){u(a,"insertAdjacentElement",function(a,e){var d=n(e);a=c.call(this,a,e);d&&B(b,e);n(a)&&z(b,e);
    return a})}function d(a,c){function e(a,e){for(var c=[];a!==e;a=a.nextSibling)c.push(a);for(e=0;e<c.length;e++)C(b,c[e])}u(a,"insertAdjacentHTML",function(a,b){a=a.toLowerCase();if("beforebegin"===a){var d=this.previousSibling;c.call(this,a,b);e(d||this.parentNode.firstChild,this)}else if("afterbegin"===a)d=this.firstChild,c.call(this,a,b),e(this.firstChild,d);else if("beforeend"===a)d=this.lastChild,c.call(this,a,b),e(d||this.firstChild,null);else if("afterend"===a)d=this.nextSibling,c.call(this,
    a,b),e(this.nextSibling,d);else throw new SyntaxError("The value provided ("+String(a)+") is not one of 'beforebegin', 'afterbegin', 'beforeend', or 'afterend'.");})}P&&u(Element.prototype,"attachShadow",function(a){return this.__CE_shadowRoot=a=P.call(this,a)});Q&&Q.get?a(Element.prototype,Q):W&&W.get?a(HTMLElement.prototype,W):w(b,function(b){a(b,{enumerable:!0,configurable:!0,get:function(){return J.call(this,!0).innerHTML},set:function(a){var b="template"===this.localName,e=b?this.content:this,
    c=I.call(document,this.namespaceURI,this.localName);for(c.innerHTML=a;0<e.childNodes.length;)M.call(e,e.childNodes[0]);for(a=b?c.content:c;0<a.childNodes.length;)K.call(e,a.childNodes[0])}})});u(Element.prototype,"setAttribute",function(a,c){if(1!==this.__CE_state)return S.call(this,a,c);var e=R.call(this,a);S.call(this,a,c);c=R.call(this,a);b.attributeChangedCallback(this,a,e,c,null)});u(Element.prototype,"setAttributeNS",function(a,c,d){if(1!==this.__CE_state)return ja.call(this,a,c,d);var e=U.call(this,
    a,c);ja.call(this,a,c,d);d=U.call(this,a,c);b.attributeChangedCallback(this,c,e,d,a)});u(Element.prototype,"removeAttribute",function(a){if(1!==this.__CE_state)return T.call(this,a);var c=R.call(this,a);T.call(this,a);null!==c&&b.attributeChangedCallback(this,a,c,null,null)});u(Element.prototype,"removeAttributeNS",function(a,c){if(1!==this.__CE_state)return ka.call(this,a,c);var d=U.call(this,a,c);ka.call(this,a,c);var e=U.call(this,a,c);d!==e&&b.attributeChangedCallback(this,c,d,e,a)});ta?c(HTMLElement.prototype,
    ta):la?c(Element.prototype,la):console.warn("Custom Elements: `Element#insertAdjacentElement` was not patched.");ua?d(HTMLElement.prototype,ua):ma?d(Element.prototype,ma):console.warn("Custom Elements: `Element#insertAdjacentHTML` was not patched.");Y(b,Element.prototype,{h:na,append:oa});ya(b)};/*
    
     Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
     This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
     The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
     The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
     Code distributed by Google as part of the polymer project is also
     subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
    */
    var Z=window.customElements;if(!Z||Z.forcePolyfill||"function"!=typeof Z.define||"function"!=typeof Z.get){var X=new v;va();wa();Y(X,DocumentFragment.prototype,{h:ha,append:ia});xa();za();document.__CE_hasRegistry=!0;var customElements=new G(X);Object.defineProperty(window,"customElements",{configurable:!0,enumerable:!0,value:customElements})};
    }).call(self);
    (function(){/*

        Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
        This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
        The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
        The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
        Code distributed by Google as part of the polymer project is also
        subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
        */
        'use strict';var aa="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},m="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;function ba(){ba=function(){};m.Symbol||(m.Symbol=ca)}var ca=function(){var a=0;return function(b){return"jscomp_symbol_"+(b||"")+a++}}();
        function p(){ba();var a=m.Symbol.iterator;a||(a=m.Symbol.iterator=m.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&aa(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return da(this)}});p=function(){}}function da(a){var b=0;return ea(function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}})}function ea(a){p();a={next:a};a[m.Symbol.iterator]=function(){return this};return a}function r(a){p();ba();p();var b=a[Symbol.iterator];return b?b.call(a):da(a)}
        function fa(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c}function t(a,b){return{index:a,l:[],v:b}}
        function ha(a,b,c,d){var e=0,f=0,g=0,h=0,k=Math.min(b-e,d-f);if(0==e&&0==f)a:{for(g=0;g<k;g++)if(a[g]!==c[g])break a;g=k}if(b==a.length&&d==c.length){h=a.length;for(var l=c.length,n=0;n<k-g&&ia(a[--h],c[--l]);)n++;h=n}e+=g;f+=g;b-=h;d-=h;if(0==b-e&&0==d-f)return[];if(e==b){for(b=t(e,0);f<d;)b.l.push(c[f++]);return[b]}if(f==d)return[t(e,b-e)];k=e;g=f;d=d-g+1;h=b-k+1;b=Array(d);for(l=0;l<d;l++)b[l]=Array(h),b[l][0]=l;for(l=0;l<h;l++)b[0][l]=l;for(l=1;l<d;l++)for(n=1;n<h;n++)if(a[k+n-1]===c[g+l-1])b[l][n]=
        b[l-1][n-1];else{var q=b[l-1][n]+1,E=b[l][n-1]+1;b[l][n]=q<E?q:E}k=b.length-1;g=b[0].length-1;d=b[k][g];for(a=[];0<k||0<g;)0==k?(a.push(2),g--):0==g?(a.push(3),k--):(h=b[k-1][g-1],l=b[k-1][g],n=b[k][g-1],q=l<n?l<h?l:h:n<h?n:h,q==h?(h==d?a.push(0):(a.push(1),d=h),k--,g--):q==l?(a.push(3),k--,d=l):(a.push(2),g--,d=n));a.reverse();b=void 0;k=[];for(g=0;g<a.length;g++)switch(a[g]){case 0:b&&(k.push(b),b=void 0);e++;f++;break;case 1:b||(b=t(e,0));b.v++;e++;b.l.push(c[f]);f++;break;case 2:b||(b=t(e,0));
        b.v++;e++;break;case 3:b||(b=t(e,0)),b.l.push(c[f]),f++}b&&k.push(b);return k}function ia(a,b){return a===b};function ja(){this.N=this.root=null;this.A=!1;this.h=this.s=this.G=this.assignedSlot=this.assignedNodes=this.i=null;this.childNodes=this.nextSibling=this.previousSibling=this.lastChild=this.firstChild=this.parentNode=this.j=void 0;this.R=this.J=!1;this.o={}}ja.prototype.toJSON=function(){return{}};function u(a){a.D||(a.D=new ja);return a.D}function v(a){return a&&a.D};var w=window.ShadyDOM||{};w.$=!(!Element.prototype.attachShadow||!Node.prototype.getRootNode);var ka=Object.getOwnPropertyDescriptor(Node.prototype,"firstChild");w.g=!!(ka&&ka.configurable&&ka.get);w.H=w.force||!w.$;var la=navigator.userAgent.match("Trident"),ma=navigator.userAgent.match("Edge");void 0===w.O&&(w.O=w.g&&(la||ma));function x(a){return(a=v(a))&&void 0!==a.firstChild}function y(a){return"ShadyRoot"===a.W}function z(a){a=a.getRootNode();if(y(a))return a}
        var A=Element.prototype,na=A.matches||A.matchesSelector||A.mozMatchesSelector||A.msMatchesSelector||A.oMatchesSelector||A.webkitMatchesSelector;function oa(a,b){if(a&&b)for(var c=Object.getOwnPropertyNames(b),d=0,e;d<c.length&&(e=c[d]);d++){var f=Object.getOwnPropertyDescriptor(b,e);f&&Object.defineProperty(a,e,f)}}function pa(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];for(d=0;d<c.length;d++)oa(a,c[d]);return a}function qa(a,b){for(var c in b)a[c]=b[c]}
        var ra=document.createTextNode(""),sa=0,ta=[];(new MutationObserver(function(){for(;ta.length;)try{ta.shift()()}catch(a){throw ra.textContent=sa++,a;}})).observe(ra,{characterData:!0});function ua(a){ta.push(a);ra.textContent=sa++}var va=!!document.contains;function wa(a,b){for(;b;){if(b==a)return!0;b=b.parentNode}return!1}
        function xa(a){for(var b=a.length-1;0<=b;b--){var c=a[b],d=c.getAttribute("id")||c.getAttribute("name");d&&"length"!==d&&isNaN(d)&&(a[d]=c)}a.item=function(b){return a[b]};a.namedItem=function(b){if("length"!==b&&isNaN(b)&&a[b])return a[b];for(var c=r(a),d=c.next();!d.done;d=c.next())if(d=d.value,(d.getAttribute("id")||d.getAttribute("name"))==b)return d;return null};return a};var B=[],ya;function za(a){ya||(ya=!0,ua(C));B.push(a)}function C(){ya=!1;for(var a=!!B.length;B.length;)B.shift()();return a}C.list=B;var Aa=/[&\u00A0"]/g,Ba=/[&\u00A0<>]/g;function Ca(a){switch(a){case "&":return"&amp;";case "<":return"&lt;";case ">":return"&gt;";case '"':return"&quot;";case "\u00a0":return"&nbsp;"}}function Da(a){for(var b={},c=0;c<a.length;c++)b[a[c]]=!0;return b}var Ea=Da("area base br col command embed hr img input keygen link meta param source track wbr".split(" ")),Fa=Da("style script xmp iframe noembed noframes plaintext noscript".split(" "));
        function Ga(a,b){"template"===a.localName&&(a=a.content);for(var c="",d=b?b(a):a.childNodes,e=0,f=d.length,g;e<f&&(g=d[e]);e++){a:{var h=g;var k=a;var l=b;switch(h.nodeType){case Node.ELEMENT_NODE:for(var n=h.localName,q="<"+n,E=h.attributes,Q=0;k=E[Q];Q++)q+=" "+k.name+'="'+k.value.replace(Aa,Ca)+'"';q+=">";h=Ea[n]?q:q+Ga(h,l)+"</"+n+">";break a;case Node.TEXT_NODE:h=h.data;h=k&&Fa[k.localName]?h:h.replace(Ba,Ca);break a;case Node.COMMENT_NODE:h="\x3c!--"+h.data+"--\x3e";break a;default:throw window.console.error(h),
        Error("not implemented");}}c+=h}return c};var D={},F=document.createTreeWalker(document,NodeFilter.SHOW_ALL,null,!1),G=document.createTreeWalker(document,NodeFilter.SHOW_ELEMENT,null,!1);function Ha(a){var b=[];F.currentNode=a;for(a=F.firstChild();a;)b.push(a),a=F.nextSibling();return b}D.parentNode=function(a){F.currentNode=a;return F.parentNode()};D.firstChild=function(a){F.currentNode=a;return F.firstChild()};D.lastChild=function(a){F.currentNode=a;return F.lastChild()};D.previousSibling=function(a){F.currentNode=a;return F.previousSibling()};
        D.nextSibling=function(a){F.currentNode=a;return F.nextSibling()};D.childNodes=Ha;D.parentElement=function(a){G.currentNode=a;return G.parentNode()};D.firstElementChild=function(a){G.currentNode=a;return G.firstChild()};D.lastElementChild=function(a){G.currentNode=a;return G.lastChild()};D.previousElementSibling=function(a){G.currentNode=a;return G.previousSibling()};D.nextElementSibling=function(a){G.currentNode=a;return G.nextSibling()};
        D.children=function(a){var b=[];G.currentNode=a;for(a=G.firstChild();a;)b.push(a),a=G.nextSibling();return xa(b)};D.innerHTML=function(a){return Ga(a,function(a){return Ha(a)})};D.textContent=function(a){switch(a.nodeType){case Node.ELEMENT_NODE:case Node.DOCUMENT_FRAGMENT_NODE:a=document.createTreeWalker(a,NodeFilter.SHOW_TEXT,null,!1);for(var b="",c;c=a.nextNode();)b+=c.nodeValue;return b;default:return a.nodeValue}};var H={},Ia=w.g,Ja=[Node.prototype,Element.prototype,HTMLElement.prototype];function I(a){var b;a:{for(b=0;b<Ja.length;b++){var c=Ja[b];if(c.hasOwnProperty(a)){b=c;break a}}b=void 0}if(!b)throw Error("Could not find descriptor for "+a);return Object.getOwnPropertyDescriptor(b,a)}
        var J=Ia?{parentNode:I("parentNode"),firstChild:I("firstChild"),lastChild:I("lastChild"),previousSibling:I("previousSibling"),nextSibling:I("nextSibling"),childNodes:I("childNodes"),parentElement:I("parentElement"),previousElementSibling:I("previousElementSibling"),nextElementSibling:I("nextElementSibling"),innerHTML:I("innerHTML"),textContent:I("textContent"),firstElementChild:I("firstElementChild"),lastElementChild:I("lastElementChild"),children:I("children")}:{},K=Ia?{firstElementChild:Object.getOwnPropertyDescriptor(DocumentFragment.prototype,
        "firstElementChild"),lastElementChild:Object.getOwnPropertyDescriptor(DocumentFragment.prototype,"lastElementChild"),children:Object.getOwnPropertyDescriptor(DocumentFragment.prototype,"children")}:{},L=Ia?{firstElementChild:Object.getOwnPropertyDescriptor(Document.prototype,"firstElementChild"),lastElementChild:Object.getOwnPropertyDescriptor(Document.prototype,"lastElementChild"),children:Object.getOwnPropertyDescriptor(Document.prototype,"children")}:{};H.M=J;H.ja=K;H.ea=L;H.parentNode=function(a){return J.parentNode.get.call(a)};
        H.firstChild=function(a){return J.firstChild.get.call(a)};H.lastChild=function(a){return J.lastChild.get.call(a)};H.previousSibling=function(a){return J.previousSibling.get.call(a)};H.nextSibling=function(a){return J.nextSibling.get.call(a)};H.childNodes=function(a){return Array.prototype.slice.call(J.childNodes.get.call(a))};H.parentElement=function(a){return J.parentElement.get.call(a)};H.previousElementSibling=function(a){return J.previousElementSibling.get.call(a)};H.nextElementSibling=function(a){return J.nextElementSibling.get.call(a)};
        H.innerHTML=function(a){return J.innerHTML.get.call(a)};H.textContent=function(a){return J.textContent.get.call(a)};H.children=function(a){switch(a.nodeType){case Node.DOCUMENT_FRAGMENT_NODE:return K.children.get.call(a);case Node.DOCUMENT_NODE:return L.children.get.call(a);default:return J.children.get.call(a)}};
        H.firstElementChild=function(a){switch(a.nodeType){case Node.DOCUMENT_FRAGMENT_NODE:return K.firstElementChild.get.call(a);case Node.DOCUMENT_NODE:return L.firstElementChild.get.call(a);default:return J.firstElementChild.get.call(a)}};H.lastElementChild=function(a){switch(a.nodeType){case Node.DOCUMENT_FRAGMENT_NODE:return K.lastElementChild.get.call(a);case Node.DOCUMENT_NODE:return L.lastElementChild.get.call(a);default:return J.lastElementChild.get.call(a)}};var M=w.O?H:D;var N={},Ka=Element.prototype.insertBefore,La=Element.prototype.replaceChild,Ma=Element.prototype.removeChild,Na=Element.prototype.setAttribute,Oa=Element.prototype.removeAttribute,Pa=Element.prototype.cloneNode,Qa=Document.prototype.importNode,Ra=Element.prototype.addEventListener,Sa=Element.prototype.removeEventListener,Ta=Window.prototype.addEventListener,Ua=Window.prototype.removeEventListener,Va=Element.prototype.dispatchEvent,Wa=Node.prototype.contains||HTMLElement.prototype.contains,Xa=Document.prototype.getElementById,
        Ya=Element.prototype.querySelector,Za=DocumentFragment.prototype.querySelector,$a=Document.prototype.querySelector,ab=Element.prototype.querySelectorAll,bb=DocumentFragment.prototype.querySelectorAll,cb=Document.prototype.querySelectorAll;N.appendChild=Element.prototype.appendChild;N.insertBefore=Ka;N.replaceChild=La;N.removeChild=Ma;N.setAttribute=Na;N.removeAttribute=Oa;N.cloneNode=Pa;N.importNode=Qa;N.addEventListener=Ra;N.removeEventListener=Sa;N.aa=Ta;N.ba=Ua;N.dispatchEvent=Va;N.contains=Wa;
        N.getElementById=Xa;N.ha=Ya;N.ka=Za;N.fa=$a;N.querySelector=function(a){switch(this.nodeType){case Node.ELEMENT_NODE:return Ya.call(this,a);case Node.DOCUMENT_NODE:return $a.call(this,a);default:return Za.call(this,a)}};N.ia=ab;N.la=bb;N.ga=cb;N.querySelectorAll=function(a){switch(this.nodeType){case Node.ELEMENT_NODE:return ab.call(this,a);case Node.DOCUMENT_NODE:return cb.call(this,a);default:return bb.call(this,a)}};function db(a){for(;a.firstChild;)a.removeChild(a.firstChild)}
        var eb=w.g,fb=document.implementation.createHTMLDocument("inert"),gb=Object.getOwnPropertyDescriptor(Node.prototype,"isConnected"),hb=gb&&gb.get,ib=Object.getOwnPropertyDescriptor(Document.prototype,"activeElement"),jb={parentElement:{get:function(){var a=v(this);(a=a&&a.parentNode)&&a.nodeType!==Node.ELEMENT_NODE&&(a=null);return void 0!==a?a:M.parentElement(this)},configurable:!0},parentNode:{get:function(){var a=v(this);a=a&&a.parentNode;return void 0!==a?a:M.parentNode(this)},configurable:!0},
        nextSibling:{get:function(){var a=v(this);a=a&&a.nextSibling;return void 0!==a?a:M.nextSibling(this)},configurable:!0},previousSibling:{get:function(){var a=v(this);a=a&&a.previousSibling;return void 0!==a?a:M.previousSibling(this)},configurable:!0},nextElementSibling:{get:function(){var a=v(this);if(a&&void 0!==a.nextSibling){for(a=this.nextSibling;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.nextSibling;return a}return M.nextElementSibling(this)},configurable:!0},previousElementSibling:{get:function(){var a=
        v(this);if(a&&void 0!==a.previousSibling){for(a=this.previousSibling;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.previousSibling;return a}return M.previousElementSibling(this)},configurable:!0}},kb={className:{get:function(){return this.getAttribute("class")||""},set:function(a){this.setAttribute("class",a)},configurable:!0}},lb={childNodes:{get:function(){if(x(this)){var a=v(this);if(!a.childNodes){a.childNodes=[];for(var b=this.firstChild;b;b=b.nextSibling)a.childNodes.push(b)}var c=a.childNodes}else c=
        M.childNodes(this);c.item=function(a){return c[a]};return c},configurable:!0},childElementCount:{get:function(){return this.children.length},configurable:!0},firstChild:{get:function(){var a=v(this);a=a&&a.firstChild;return void 0!==a?a:M.firstChild(this)},configurable:!0},lastChild:{get:function(){var a=v(this);a=a&&a.lastChild;return void 0!==a?a:M.lastChild(this)},configurable:!0},textContent:{get:function(){if(x(this)){for(var a=[],b=0,c=this.childNodes,d;d=c[b];b++)d.nodeType!==Node.COMMENT_NODE&&
        a.push(d.textContent);return a.join("")}return M.textContent(this)},set:function(a){if("undefined"===typeof a||null===a)a="";switch(this.nodeType){case Node.ELEMENT_NODE:case Node.DOCUMENT_FRAGMENT_NODE:if(!x(this)&&eb){var b=this.firstChild;(b!=this.lastChild||b&&b.nodeType!=Node.TEXT_NODE)&&db(this);H.M.textContent.set.call(this,a)}else db(this),(0<a.length||this.nodeType===Node.ELEMENT_NODE)&&this.appendChild(document.createTextNode(a));break;default:this.nodeValue=a}},configurable:!0},firstElementChild:{get:function(){var a=
        v(this);if(a&&void 0!==a.firstChild){for(a=this.firstChild;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.nextSibling;return a}return M.firstElementChild(this)},configurable:!0},lastElementChild:{get:function(){var a=v(this);if(a&&void 0!==a.lastChild){for(a=this.lastChild;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.previousSibling;return a}return M.lastElementChild(this)},configurable:!0},children:{get:function(){return x(this)?xa(Array.prototype.filter.call(this.childNodes,function(a){return a.nodeType===Node.ELEMENT_NODE})):
        M.children(this)},configurable:!0},innerHTML:{get:function(){return x(this)?Ga("template"===this.localName?this.content:this):M.innerHTML(this)},set:function(a){var b="template"===this.localName?this.content:this;db(b);var c=this.localName||"div";c=this.namespaceURI&&this.namespaceURI!==fb.namespaceURI?fb.createElementNS(this.namespaceURI,c):fb.createElement(c);eb?H.M.innerHTML.set.call(c,a):c.innerHTML=a;for(a="template"===this.localName?c.content:c;a.firstChild;)b.appendChild(a.firstChild)},configurable:!0}},
        mb={shadowRoot:{get:function(){var a=v(this);return a&&a.N||null},configurable:!0}},nb={activeElement:{get:function(){var a=ib&&ib.get?ib.get.call(document):w.g?void 0:document.activeElement;if(a&&a.nodeType){var b=!!y(this);if(this===document||b&&this.host!==a&&N.contains.call(this.host,a)){for(b=z(a);b&&b!==this;)a=b.host,b=z(a);a=this===document?b?null:a:b===this?a:null}else a=null}else a=null;return a},set:function(){},configurable:!0}};
        function O(a,b,c){for(var d in b){var e=Object.getOwnPropertyDescriptor(a,d);e&&e.configurable||!e&&c?Object.defineProperty(a,d,b[d]):c&&console.warn("Could not define",d,"on",a)}}function P(a){O(a,jb);O(a,kb);O(a,lb);O(a,nb)}
        function ob(){var a=R.prototype;a.__proto__=DocumentFragment.prototype;O(a,jb,!0);O(a,lb,!0);O(a,nb,!0);Object.defineProperties(a,{nodeType:{value:Node.DOCUMENT_FRAGMENT_NODE,configurable:!0},nodeName:{value:"#document-fragment",configurable:!0},nodeValue:{value:null,configurable:!0}});["localName","namespaceURI","prefix"].forEach(function(b){Object.defineProperty(a,b,{value:void 0,configurable:!0})});["ownerDocument","baseURI","isConnected"].forEach(function(b){Object.defineProperty(a,b,{get:function(){return this.host[b]},
        configurable:!0})})}var pb=w.g?function(){}:function(a){var b=u(a);b.J||(b.J=!0,O(a,jb,!0),O(a,kb,!0))},qb=w.g?function(){}:function(a){u(a).R||(O(a,lb,!0),O(a,mb,!0))};var rb=M.childNodes;function sb(a,b,c){pb(a);c=c||null;var d=u(a),e=u(b),f=c?u(c):null;d.previousSibling=c?f.previousSibling:b.lastChild;if(f=v(d.previousSibling))f.nextSibling=a;if(f=v(d.nextSibling=c))f.previousSibling=a;d.parentNode=b;c?c===e.firstChild&&(e.firstChild=a):(e.lastChild=a,e.firstChild||(e.firstChild=a));e.childNodes=null}
        function tb(a){var b=u(a);if(void 0===b.firstChild){b.childNodes=null;var c=rb(a);b.firstChild=c[0]||null;b.lastChild=c[c.length-1]||null;qb(a);for(b=0;b<c.length;b++){var d=c[b],e=u(d);e.parentNode=a;e.nextSibling=c[b+1]||null;e.previousSibling=c[b-1]||null;pb(d)}}};var ub=M.parentNode,vb=M.childNodes,wb={},S=w.deferConnectionCallbacks&&"loading"===document.readyState,T;function xb(a){var b=[];do b.unshift(a);while(a=a.parentNode);return b}
        function R(a,b,c){if(a!==wb)throw new TypeError("Illegal constructor");this.W="ShadyRoot";this.host=b;this.Z=c&&c.mode;tb(b);a=u(b);a.root=this;a.N="closed"!==this.Z?this:null;a=u(this);a.firstChild=a.lastChild=a.parentNode=a.nextSibling=a.previousSibling=null;a.childNodes=[];this.L=this.u=!1;this.c=this.b=this.a=null;U(this)}function U(a){a.u||(a.u=!0,za(function(){return yb(a)}))}
        function yb(a){for(var b;a;){a.u&&(b=a);a:{var c=a;a=c.host.getRootNode();if(y(a))for(var d=c.host.childNodes,e=0;e<d.length;e++)if(c=d[e],"slot"==c.localName)break a;a=void 0}}b&&b._renderRoot()}
        R.prototype._renderRoot=function(){var a=S;S=!0;this.u=!1;if(this.a){zb(this);for(var b=0;b<this.a.length;b++){var c=this.a[b];var d=v(c),e=d.assignedNodes;d.assignedNodes=[];d.h=[];if(d.G=e)for(d=0;d<e.length;d++){var f=v(e[d]);f.s=f.assignedSlot;f.assignedSlot===c&&(f.assignedSlot=null)}}for(c=this.host.firstChild;c;c=c.nextSibling)Ab(this,c);for(b=0;b<this.a.length;b++){c=this.a[b];e=v(c);if(!e.assignedNodes.length)for(d=c.firstChild;d;d=d.nextSibling)Ab(this,d,c);(d=(d=v(c.parentNode))&&d.root)&&
        Bb(d)&&d._renderRoot();Cb(this,e.h,e.assignedNodes);if(d=e.G){for(f=0;f<d.length;f++)v(d[f]).s=null;e.G=null;d.length>e.assignedNodes.length&&(e.A=!0)}e.A&&(e.A=!1,Db(this,c))}b=this.a;c=[];for(e=0;e<b.length;e++)d=b[e].parentNode,(f=v(d))&&f.root||!(0>c.indexOf(d))||c.push(d);for(b=0;b<c.length;b++){e=c[b];d=e===this?this.host:e;f=[];e=e.childNodes;for(var g=0;g<e.length;g++){var h=e[g];if("slot"==h.localName){h=v(h).h;for(var k=0;k<h.length;k++)f.push(h[k])}else f.push(h)}e=void 0;g=vb(d);h=ha(f,
        f.length,g,g.length);for(var l=k=0;k<h.length&&(e=h[k]);k++){for(var n=0,q;n<e.l.length&&(q=e.l[n]);n++)ub(q)===d&&N.removeChild.call(d,q),g.splice(e.index+l,1);l-=e.v}for(l=0;l<h.length&&(e=h[l]);l++)for(k=g[e.index],n=e.index;n<e.index+e.v;n++)q=f[n],N.insertBefore.call(d,q,k),g.splice(n,0,q)}}if(!this.L)for(q=this.host.childNodes,c=0,b=q.length;c<b;c++)e=q[c],d=v(e),ub(e)!==this.host||"slot"!==e.localName&&d.assignedSlot||N.removeChild.call(this.host,e);this.L=!0;S=a;T&&T()};
        function Ab(a,b,c){var d=u(b),e=d.s;d.s=null;c||(c=(a=a.b[b.slot||"__catchall"])&&a[0]);c?(u(c).assignedNodes.push(b),d.assignedSlot=c):d.assignedSlot=void 0;e!==d.assignedSlot&&d.assignedSlot&&(u(d.assignedSlot).A=!0)}function Cb(a,b,c){for(var d=0,e;d<c.length&&(e=c[d]);d++)if("slot"==e.localName){var f=v(e).assignedNodes;f&&f.length&&Cb(a,b,f)}else b.push(c[d])}function Db(a,b){N.dispatchEvent.call(b,new Event("slotchange"));b=v(b);b.assignedSlot&&Db(a,b.assignedSlot)}
        function zb(a){if(a.c&&a.c.length){for(var b=a.c,c,d=0;d<b.length;d++){var e=b[d];tb(e);tb(e.parentNode);var f=Eb(e);a.b[f]?(c=c||{},c[f]=!0,a.b[f].push(e)):a.b[f]=[e];a.a.push(e)}if(c)for(var g in c)a.b[g]=Fb(a.b[g]);a.c=[]}}function Eb(a){var b=a.name||a.getAttribute("name")||"__catchall";return a.U=b}function Fb(a){return a.sort(function(a,c){a=xb(a);for(var b=xb(c),e=0;e<a.length;e++){c=a[e];var f=b[e];if(c!==f)return a=Array.from(c.parentNode.childNodes),a.indexOf(c)-a.indexOf(f)}})}
        function Bb(a){zb(a);return!(!a.a||!a.a.length)}
        if(window.customElements&&w.H){var V=new Map;T=function(){var a=Array.from(V);V.clear();a=r(a);for(var b=a.next();!b.done;b=a.next()){b=r(b.value);var c=b.next().value;b.next().value?c.S():c.T()}};S&&document.addEventListener("readystatechange",function(){S=!1;T()},{once:!0});var Gb=function(a,b,c){var d=0,e="__isConnected"+d++;if(b||c)a.prototype.connectedCallback=a.prototype.S=function(){S?V.set(this,!0):this[e]||(this[e]=!0,b&&b.call(this))},a.prototype.disconnectedCallback=a.prototype.T=function(){S?
        this.isConnected||V.set(this,!1):this[e]&&(this[e]=!1,c&&c.call(this))};return a},Hb=window.customElements.define;Object.defineProperty(window.CustomElementRegistry.prototype,"define",{value:function(a,b){var c=b.prototype.connectedCallback,d=b.prototype.disconnectedCallback;Hb.call(window.customElements,a,Gb(b,c,d));b.prototype.connectedCallback=c;b.prototype.disconnectedCallback=d}})};var Ib=M.parentNode;
        function Jb(a,b,c){if(b===a)throw Error("Failed to execute 'appendChild' on 'Node': The new child element contains the parent.");if(c){var d=v(c);d=d&&d.parentNode;if(void 0!==d&&d!==a||void 0===d&&Ib(c)!==a)throw Error("Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.");}if(c===b)return b;b.parentNode&&Kb(b.parentNode,b);var e,f;if(!b.__noInsertionPoint){if(f=e=z(a)){var g;"slot"===b.localName?g=[b]:b.querySelectorAll&&
        (g=b.querySelectorAll("slot"));f=g&&g.length?g:void 0}f&&(g=e,d=f,g.c=g.c||[],g.a=g.a||[],g.b=g.b||{},g.c.push.apply(g.c,[].concat(d instanceof Array?d:fa(r(d)))))}("slot"===a.localName||f)&&(e=e||z(a))&&U(e);if(x(a)){e=c;qb(a);f=u(a);void 0!==f.firstChild&&(f.childNodes=null);if(b.nodeType===Node.DOCUMENT_FRAGMENT_NODE){f=b.childNodes;for(g=0;g<f.length;g++)sb(f[g],a,e);e=u(b);f=void 0!==e.firstChild?null:void 0;e.firstChild=e.lastChild=f;e.childNodes=f}else sb(b,a,e);e=v(a);if(Lb(a)){U(e.root);
        var h=!0}else e.root&&(h=!0)}h||(h=y(a)?a.host:a,c?(c=Mb(c),N.insertBefore.call(h,b,c)):N.appendChild.call(h,b));Nb(a,b);return b}
        function Kb(a,b){if(b.parentNode!==a)throw Error("The node to be removed is not a child of this node: "+b);var c=z(b),d=v(a);if(x(a)){var e=u(b),f=u(a);b===f.firstChild&&(f.firstChild=e.nextSibling);b===f.lastChild&&(f.lastChild=e.previousSibling);var g=e.previousSibling,h=e.nextSibling;g&&(u(g).nextSibling=h);h&&(u(h).previousSibling=g);e.parentNode=e.previousSibling=e.nextSibling=void 0;void 0!==f.childNodes&&(f.childNodes=null);if(Lb(a)){U(d.root);var k=!0}}Ob(b);if(c){(e=a&&"slot"===a.localName)&&
        (k=!0);if(c.a){zb(c);f=c.b;for(Z in f)for(g=f[Z],h=0;h<g.length;h++){var l=g[h];if(wa(b,l)){g.splice(h,1);var n=c.a.indexOf(l);0<=n&&c.a.splice(n,1);h--;n=v(l);if(l=n.h)for(var q=0;q<l.length;q++){var E=l[q],Q=ub(E);Q&&N.removeChild.call(Q,E)}n.h=[];n.assignedNodes=[];n=!0}}var Z=n}else Z=void 0;(Z||e)&&U(c)}k||(k=y(a)?a.host:a,(!d.root&&"slot"!==b.localName||k===Ib(b))&&N.removeChild.call(k,b));Nb(a,null,b);return b}
        function Ob(a){var b=v(a);if(b&&void 0!==b.j){b=a.childNodes;for(var c=0,d=b.length,e;c<d&&(e=b[c]);c++)Ob(e)}if(a=v(a))a.j=void 0}function Mb(a){var b=a;a&&"slot"===a.localName&&(b=(b=(b=v(a))&&b.h)&&b.length?b[0]:Mb(a.nextSibling));return b}function Lb(a){return(a=(a=v(a))&&a.root)&&Bb(a)}
        function Pb(a,b){if("slot"===b)a=a.parentNode,Lb(a)&&U(v(a).root);else if("slot"===a.localName&&"name"===b&&(b=z(a))){if(b.a){var c=a.U,d=Eb(a);if(d!==c){c=b.b[c];var e=c.indexOf(a);0<=e&&c.splice(e,1);c=b.b[d]||(b.b[d]=[]);c.push(a);1<c.length&&(b.b[d]=Fb(c))}}U(b)}}function Nb(a,b,c){if(a=(a=v(a))&&a.i)b&&a.addedNodes.push(b),c&&a.removedNodes.push(c),Qb(a)}
        function Rb(a){if(a&&a.nodeType){var b=u(a),c=b.j;void 0===c&&(y(a)?(c=a,b.j=c):(c=(c=a.parentNode)?Rb(c):a,N.contains.call(document.documentElement,a)&&(b.j=c)));return c}}function Sb(a,b,c){var d=[];Tb(a.childNodes,b,c,d);return d}function Tb(a,b,c,d){for(var e=0,f=a.length,g;e<f&&(g=a[e]);e++){var h;if(h=g.nodeType===Node.ELEMENT_NODE){h=g;var k=b,l=c,n=d,q=k(h);q&&n.push(h);l&&l(q)?h=q:(Tb(h.childNodes,k,l,n),h=void 0)}if(h)break}}var Ub=null;
        function Vb(a,b,c){Ub||(Ub=window.ShadyCSS&&window.ShadyCSS.ScopingShim);Ub&&"class"===b?Ub.setElementClass(a,c):(N.setAttribute.call(a,b,c),Pb(a,b))}function Wb(a,b){if(a.ownerDocument!==document||"template"===a.localName)return N.importNode.call(document,a,b);var c=N.importNode.call(document,a,!1);if(b){a=a.childNodes;b=0;for(var d;b<a.length;b++)d=Wb(a[b],!0),c.appendChild(d)}return c};function Xb(){this.c=!1;this.addedNodes=[];this.removedNodes=[];this.w=new Set}function Qb(a){a.c||(a.c=!0,ua(function(){Yb(a)}))}function Yb(a){if(a.c){a.c=!1;var b=a.takeRecords();b.length&&a.w.forEach(function(a){a(b)})}}Xb.prototype.takeRecords=function(){if(this.addedNodes.length||this.removedNodes.length){var a=[{addedNodes:this.addedNodes,removedNodes:this.removedNodes}];this.addedNodes=[];this.removedNodes=[];return a}return[]};
        function Zb(a,b){var c=u(a);c.i||(c.i=new Xb);c.i.w.add(b);var d=c.i;return{V:b,Y:d,X:a,takeRecords:function(){return d.takeRecords()}}}function $b(a){var b=a&&a.Y;b&&(b.w.delete(a.V),b.w.size||(u(a.X).i=null))}
        function ac(a,b){var c=b.getRootNode();return a.map(function(a){var b=c===a.target.getRootNode();if(b&&a.addedNodes){if(b=Array.from(a.addedNodes).filter(function(a){return c===a.getRootNode()}),b.length)return a=Object.create(a),Object.defineProperty(a,"addedNodes",{value:b,configurable:!0}),a}else if(b)return a}).filter(function(a){return a})};var W="__eventWrappers"+Date.now(),bc=function(){var a=Object.getOwnPropertyDescriptor(Event.prototype,"composed");return a?function(b){return a.get.call(b)}:null}(),cc={blur:!0,focus:!0,focusin:!0,focusout:!0,click:!0,dblclick:!0,mousedown:!0,mouseenter:!0,mouseleave:!0,mousemove:!0,mouseout:!0,mouseover:!0,mouseup:!0,wheel:!0,beforeinput:!0,input:!0,keydown:!0,keyup:!0,compositionstart:!0,compositionupdate:!0,compositionend:!0,touchstart:!0,touchend:!0,touchmove:!0,touchcancel:!0,pointerover:!0,
        pointerenter:!0,pointerdown:!0,pointermove:!0,pointerup:!0,pointercancel:!0,pointerout:!0,pointerleave:!0,gotpointercapture:!0,lostpointercapture:!0,dragstart:!0,drag:!0,dragenter:!0,dragleave:!0,dragover:!0,drop:!0,dragend:!0,DOMActivate:!0,DOMFocusIn:!0,DOMFocusOut:!0,keypress:!0},dc={DOMAttrModified:!0,DOMAttributeNameChanged:!0,DOMCharacterDataModified:!0,DOMElementNameChanged:!0,DOMNodeInserted:!0,DOMNodeInsertedIntoDocument:!0,DOMNodeRemoved:!0,DOMNodeRemovedFromDocument:!0,DOMSubtreeModified:!0};
        function ec(a,b){var c=[],d=a;for(a=a===window?window:a.getRootNode();d;)c.push(d),d=d.assignedSlot?d.assignedSlot:d.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&d.host&&(b||d!==a)?d.host:d.parentNode;c[c.length-1]===document&&c.push(window);return c}function fc(a,b){if(!y)return a;a=ec(a,!0);for(var c=0,d,e,f,g;c<b.length;c++)if(d=b[c],f=d===window?window:d.getRootNode(),f!==e&&(g=a.indexOf(f),e=f),!y(f)||-1<g)return d}
        var gc={get composed(){void 0===this.m&&(bc?this.m=bc(this):!1!==this.isTrusted&&(this.m=cc[this.type]));return this.m||!1},composedPath:function(){this.I||(this.I=ec(this.__target,this.composed));return this.I},get target(){return fc(this.currentTarget,this.composedPath())},get relatedTarget(){if(!this.C)return null;this.K||(this.K=ec(this.C,!0));return fc(this.currentTarget,this.K)},stopPropagation:function(){Event.prototype.stopPropagation.call(this);this.B=!0},stopImmediatePropagation:function(){Event.prototype.stopImmediatePropagation.call(this);
        this.B=this.P=!0}};function hc(a){function b(b,d){b=new a(b,d);b.m=d&&!!d.composed;return b}qa(b,a);b.prototype=a.prototype;return b}var ic={focus:!0,blur:!0};function jc(a){return a.__target!==a.target||a.C!==a.relatedTarget}function kc(a,b,c){if(c=b.__handlers&&b.__handlers[a.type]&&b.__handlers[a.type][c])for(var d=0,e;(e=c[d])&&(!jc(a)||a.target!==a.relatedTarget)&&(e.call(b,a),!a.P);d++);}
        function lc(a){var b=a.composedPath();Object.defineProperty(a,"currentTarget",{get:function(){return d},configurable:!0});for(var c=b.length-1;0<=c;c--){var d=b[c];kc(a,d,"capture");if(a.B)return}Object.defineProperty(a,"eventPhase",{get:function(){return Event.AT_TARGET}});var e;for(c=0;c<b.length;c++){d=b[c];var f=v(d);f=f&&f.root;if(0===c||f&&f===e)if(kc(a,d,"bubble"),d!==window&&(e=d.getRootNode()),a.B)break}}
        function mc(a,b,c,d,e,f){for(var g=0;g<a.length;g++){var h=a[g],k=h.type,l=h.capture,n=h.once,q=h.passive;if(b===h.node&&c===k&&d===l&&e===n&&f===q)return g}return-1}
        function nc(a,b,c){if(b){var d=typeof b;if("function"===d||"object"===d)if("object"!==d||b.handleEvent&&"function"===typeof b.handleEvent){var e=this instanceof Window?N.aa:N.addEventListener;if(dc[a])return e.call(this,a,b,c);if(c&&"object"===typeof c){var f=!!c.capture;var g=!!c.once;var h=!!c.passive}else f=!!c,h=g=!1;var k=c&&c.F||this,l=b[W];if(l){if(-1<mc(l,k,a,f,g,h))return}else b[W]=[];l=function(e){g&&this.removeEventListener(a,b,c);e.__target||oc(e);if(k!==this){var f=Object.getOwnPropertyDescriptor(e,
        "currentTarget");Object.defineProperty(e,"currentTarget",{get:function(){return k},configurable:!0})}if(!y(k)||-1!=e.composedPath().indexOf(k))if(e.composed||-1<e.composedPath().indexOf(k))if(jc(e)&&e.target===e.relatedTarget)e.eventPhase===Event.BUBBLING_PHASE&&e.stopImmediatePropagation();else if(e.eventPhase===Event.CAPTURING_PHASE||e.bubbles||e.target===k||k instanceof Window){var h="function"===d?b.call(k,e):b.handleEvent&&b.handleEvent(e);k!==this&&(f?(Object.defineProperty(e,"currentTarget",
        f),f=null):delete e.currentTarget);return h}};b[W].push({node:k,type:a,capture:f,once:g,passive:h,ca:l});ic[a]?(this.__handlers=this.__handlers||{},this.__handlers[a]=this.__handlers[a]||{capture:[],bubble:[]},this.__handlers[a][f?"capture":"bubble"].push(l)):e.call(this,a,l,c)}}}
        function pc(a,b,c){if(b){var d=this instanceof Window?N.ba:N.removeEventListener;if(dc[a])return d.call(this,a,b,c);if(c&&"object"===typeof c){var e=!!c.capture;var f=!!c.once;var g=!!c.passive}else e=!!c,g=f=!1;var h=c&&c.F||this,k=void 0;var l=null;try{l=b[W]}catch(n){}l&&(f=mc(l,h,a,e,f,g),-1<f&&(k=l.splice(f,1)[0].ca,l.length||(b[W]=void 0)));d.call(this,a,k||b,c);k&&ic[a]&&this.__handlers&&this.__handlers[a]&&(a=this.__handlers[a][e?"capture":"bubble"],k=a.indexOf(k),-1<k&&a.splice(k,1))}}
        function qc(){for(var a in ic)window.addEventListener(a,function(a){a.__target||(oc(a),lc(a))},!0)}function oc(a){a.__target=a.target;a.C=a.relatedTarget;if(w.g){var b=Object.getPrototypeOf(a);if(!b.hasOwnProperty("__patchProto")){var c=Object.create(b);c.da=b;oa(c,gc);b.__patchProto=c}a.__proto__=b.__patchProto}else oa(a,gc)}var rc=hc(window.Event),sc=hc(window.CustomEvent),tc=hc(window.MouseEvent);
        function uc(){window.Event=rc;window.CustomEvent=sc;window.MouseEvent=tc;qc();if(!bc&&Object.getOwnPropertyDescriptor(Event.prototype,"isTrusted")){var a=function(){var a=new MouseEvent("click",{bubbles:!0,cancelable:!0,composed:!0});this.dispatchEvent(a)};Element.prototype.click?Element.prototype.click=a:HTMLElement.prototype.click&&(HTMLElement.prototype.click=a)}};function vc(a){var b=a.getRootNode();y(b)&&yb(b);return(a=v(a))&&a.assignedSlot||null}
        var wc={addEventListener:nc.bind(window),removeEventListener:pc.bind(window)},xc={addEventListener:nc,removeEventListener:pc,appendChild:function(a){return Jb(this,a)},insertBefore:function(a,b){return Jb(this,a,b)},removeChild:function(a){return Kb(this,a)},replaceChild:function(a,b){Jb(this,a,b);Kb(this,b);return a},cloneNode:function(a){if("template"==this.localName)var b=N.cloneNode.call(this,a);else if(b=N.cloneNode.call(this,!1),a&&b.nodeType!==Node.ATTRIBUTE_NODE){a=this.childNodes;for(var c=
        0,d;c<a.length;c++)d=a[c].cloneNode(!0),b.appendChild(d)}return b},getRootNode:function(){return Rb(this)},contains:function(a){return wa(this,a)},dispatchEvent:function(a){C();return N.dispatchEvent.call(this,a)}};
        Object.defineProperties(xc,{isConnected:{get:function(){if(hb&&hb.call(this))return!0;if(this.nodeType==Node.DOCUMENT_FRAGMENT_NODE)return!1;var a=this.ownerDocument;if(va){if(N.contains.call(a,this))return!0}else if(a.documentElement&&N.contains.call(a.documentElement,this))return!0;for(a=this;a&&!(a instanceof Document);)a=a.parentNode||(y(a)?a.host:void 0);return!!(a&&a instanceof Document)},configurable:!0}});
        var yc={get assignedSlot(){return vc(this)}},zc={querySelector:function(a){return Sb(this,function(b){return na.call(b,a)},function(a){return!!a})[0]||null},querySelectorAll:function(a,b){if(b){b=Array.prototype.slice.call(N.querySelectorAll.call(this,a));var c=this.getRootNode();return b.filter(function(a){return a.getRootNode()==c})}return Sb(this,function(b){return na.call(b,a)})}},Ac={assignedNodes:function(a){if("slot"===this.localName){var b=this.getRootNode();y(b)&&yb(b);return(b=v(this))?
        (a&&a.flatten?b.h:b.assignedNodes)||[]:[]}}},Bc=pa({setAttribute:function(a,b){Vb(this,a,b)},removeAttribute:function(a){N.removeAttribute.call(this,a);Pb(this,a)},attachShadow:function(a){if(!this)throw"Must provide a host.";if(!a)throw"Not enough arguments.";return new R(wb,this,a)},get slot(){return this.getAttribute("slot")},set slot(a){Vb(this,"slot",a)},get assignedSlot(){return vc(this)}},zc,Ac);Object.defineProperties(Bc,mb);
        var Cc=pa({importNode:function(a,b){return Wb(a,b)},getElementById:function(a){return Sb(this,function(b){return b.id==a},function(a){return!!a})[0]||null}},zc);Object.defineProperties(Cc,{_activeElement:nb.activeElement});
        for(var Dc=HTMLElement.prototype.blur,Ec={blur:function(){var a=v(this);(a=(a=a&&a.root)&&a.activeElement)?a.blur():Dc.call(this)}},X={},Fc=r(Object.getOwnPropertyNames(Document.prototype)),Gc=Fc.next();!Gc.done;X={f:X.f},Gc=Fc.next())X.f=Gc.value,"on"===X.f.substring(0,2)&&Object.defineProperty(Ec,X.f,{set:function(a){return function(b){var c=u(this),d=a.f.substring(2);c.o[a.f]&&this.removeEventListener(d,c.o[a.f]);this.addEventListener(d,b,{});c.o[a.f]=b}}(X),get:function(a){return function(){var b=
        v(this);return b&&b.o[a.f]}}(X),configurable:!0});var Hc={addEventListener:function(a,b,c){"object"!==typeof c&&(c={capture:!!c});c.F=this;this.host.addEventListener(a,b,c)},removeEventListener:function(a,b,c){"object"!==typeof c&&(c={capture:!!c});c.F=this;this.host.removeEventListener(a,b,c)},getElementById:function(a){return Sb(this,function(b){return b.id==a},function(a){return!!a})[0]||null}};
        function Y(a,b){for(var c=Object.getOwnPropertyNames(b),d=0;d<c.length;d++){var e=c[d],f=Object.getOwnPropertyDescriptor(b,e);f.value?a[e]=f.value:Object.defineProperty(a,e,f)}};if(w.H){window.ShadyDOM={inUse:w.H,patch:function(a){qb(a);pb(a);return a},isShadyRoot:y,enqueue:za,flush:C,settings:w,filterMutations:ac,observeChildren:Zb,unobserveChildren:$b,nativeMethods:N,nativeTree:M,deferConnectionCallbacks:w.deferConnectionCallbacks};uc();var Ic=window.customElements&&window.customElements.nativeHTMLElement||HTMLElement;Y(R.prototype,Hc);Y(window.Node.prototype,xc);Y(window.Window.prototype,wc);Y(window.Text.prototype,yc);Y(window.DocumentFragment.prototype,zc);Y(window.Element.prototype,
        Bc);Y(window.Document.prototype,Cc);window.HTMLSlotElement&&Y(window.HTMLSlotElement.prototype,Ac);Y(Ic.prototype,Ec);w.g&&(P(window.Node.prototype),P(window.Text.prototype),P(window.DocumentFragment.prototype),P(window.Element.prototype),P(Ic.prototype),P(window.Document.prototype),window.HTMLSlotElement&&P(window.HTMLSlotElement.prototype));ob();window.ShadowRoot=R};}).call(this);